# Generated by Django 4.2.9 on 2026-03-17 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_remove_user_is_verified_remove_user_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'admin'), ('technician', 'technician'), ('support', 'customer_support')], default='technician', max_length=30),
        ),
    ]
