services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: mpaya_dev
      POSTGRES_USER: mpaya
      POSTGRES_PASSWORD: mpaya_secret
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"

  redis:
    image: redis:7-alpine


  api:
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.development
      - SECRET_KEY=dev-secret-key-change-in-production
      - DB_NAME=mpaya_dev
      - DB_USER=mpaya
      - DB_PASSWORD=mpaya_secret
      - DB_HOST=db
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis

  celery:
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: celery -A config worker --loglevel=info
    volumes:
      - .:/app
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.development
      - SECRET_KEY=dev-secret-key-change-in-production
      - DB_NAME=mpaya_dev
      - DB_USER=mpaya
      - DB_PASSWORD=mpaya_secret
      - DB_HOST=db
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis

  celery-beat:
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: celery -A config beat --loglevel=info
    volumes:
      - .:/app
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.development
      - SECRET_KEY=dev-secret-key-change-in-production
      - DB_NAME=mpaya_dev
      - DB_USER=mpaya
      - DB_PASSWORD=mpaya_secret
      - DB_HOST=db
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis

volumes:
  postgres_data:
